create table request(
    id int primary key generated by default as identity,
    address varchar,
    request_timestamp timestamp
);

create table users(
    id int primary key generated by default as identity,
    username varchar unique not null,
    password varchar
);