create table users(
    id int primary key generated by default as identity,
    username varchar unique not null,
    password varchar
);

create table request(
    id int primary key generated by default as identity,
    address varchar,
    request_timestamp timestamp,
    user_id int references users(id) on delete cascade
);
