create table users(
                      id int primary key generated by default as identity,
                      username varchar unique not null,
                      password varchar
);

create table request(
                        id int primary key generated by default as identity,
                        address varchar,
                        request_timestamp timestamp,
                        user_id int references users(id) on delete cascade
);

create table weather(
    id int primary key generated by default as identity,
    temperature int,
    wind int,
    description varchar,
    request_id int references request(id) on delete cascade
);

create table days(
    id int primary key generated by default as identity,
    date int,
    temperature int,
    wind int,
    weather_id int references weather(id) on delete cascade
);