jwt_secret: "secret"
spring:
  application:
    name: weather
  datasource:
    url: "jdbc:postgresql://localhost:5433/weather_db"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml